version: '3.7'
services:
  opoapi-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    container_name: opoapi-backend
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    container_name: my_mongo

volumes:
  mongo_data:
        