version: '3.7'
services:
  opoapi-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    container_name: opoapi-backend
    links:
      - my_mongo

        